name: 'ga-delete-application-argo'
description: 'Delete an ArgoCD application if exists'
inputs:
  argoserver:
    description: 'Host of the ArgoCD server'
    required: true
  application:
    description: 'Name of the application to delete'
    required: true
  token:
    description: 'ArgoCD token required to send API requests'
    required: true
outputs:
  deleted:
    description: 'Boolean representation of the application being deleted or not'
  reason:
    description: 'Reason of failure in cas of it'
runs:
  using: 'docker'
  image: 'Dockerfile'
